// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/notification/Alert.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppColorInput: typeof import('./src/components/ui/AppColorInput.vue')['default']
    AppImage: typeof import('./src/components/ui/AppImage.vue')['default']
    AppImageDropZone: typeof import('./src/components/ui/AppImageDropZone.vue')['default']
    AppLabelsPicker: typeof import('./src/components/ui/AppLabelsPicker.vue')['default']
    AppLoader: typeof import('./src/components/ui/AppLoader.vue')['default']
    AppPageHeading: typeof import('./src/components/ui/AppPageHeading.vue')['default']
    BoardCard: typeof import('./src/components/board/BoardCard.vue')['default']
    BoardColumn: typeof import('./src/components/board/BoardColumn.vue')['default']
    BoardDragDrop: typeof import('./src/components/board/BoardDragDrop.vue')['default']
    BoardMenu: typeof import('./src/components/board/BoardMenu.vue')['default']
    Comments: typeof import('./src/components/task/Comments.vue')['default']
    Drawer: typeof import('./src/components/navigation/Drawer.vue')['default']
    NavBar: typeof import('./src/components/navigation/NavBar.vue')['default']
    Notifications: typeof import('./src/components/notification/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/task/TaskCard.vue')['default']
    TaskCreator: typeof import('./src/components/task/TaskCreator.vue')['default']
  }
}

export {}
